apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-test-scan
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/cgsamp/tanzu-java-web-app
      ref:
        branch: main
